version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ikaros
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql